### PR TITLE
add try catch to continue loading in case of errors, add logging

### PR DESCRIPTION
**Pull request by hg42**
Any single error in any script stopped loading completely. Instead it should only stop the buggy script.
A try/catch solves this.

I also added some logging to group messages by file.

### CODE REVIEW

**Comment by Sporif** [comment]
(I'm really sorry for the late reply, I don't think GitHub sent me an email for this. Either that or I misconfigured something badly.)

Thank you for opening a PR, it looks great. Just one thing, the logging makes it look like all files/directories are loaded. I think we should also add logging for each filetype loaded, when a file is ignored and when it's not a file. Do you want to do that or should I?

**Comment by hg42** [comment]
Hi, I forgot about this PR, too :-)

I mainly wanted to group outputs from the scripts and their loading process. It happened to be useful for try/catch errors, too.

You are right, I didn't look at the missing else case.
I'll have a look at this weekend.

**Comment by hg42** [comment]
I took a different approach, because ignored files are not very interesting.
So I first detect the type and only add logging for files that are matching.
This also allowed to added the type to the output.
Directories were already detected outside of the logging part.

**Comment by hg42** [comment]
btw. the loader still works in FF 66.0a1

**Comment by Sporif** [comment]
Yeah that looks good, I'll merge it.

**Comment by hg42** [comment]
thanks...

**Pull request merged**
